// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Nicola Mustone

// Class assignments follow the publisher's lists on physical PDF pages 270–272.
export const TOME_OF_HEROES_CLASS_LISTS: Readonly<
  Record<string, readonly string[]>
> = {
  Bard: [
    "Hypnic Jerk",
    "Adjust Position",
    "Damaging Intel",
    "Glare",
    "Heart to Heart",
    "Ill-Fated Word",
    "Less Fool, I",
    "Lightless Torch",
    "Muted Foe",
    "Outmaneuver",
    "Sneer",
    "Subliminal Aversion",
    "Butterfly Effect",
    "Fey-Touched Blade",
    "Frenzied Bolt",
    "Fuse Armor",
    "Glyph of Shifting",
    "Portal Trap",
    "Shadow's Brand",
    "Silvershout",
    "Spite",
    "Armored Formation",
    "Bolster Fortifications",
    "Dimensional Shove",
    "Iron Gut",
    "Jagged Forcelance",
    "Never Surrender",
    "Oathbound Implement",
    "Shared Frenzy",
    "Dreamwine",
    "Harry",
    "Hypnagogia",
    "Inspiring Speech",
    "Mass Faerie Fire",
    "Power Word Rend",
    "Reaper's Knell",
    "Reposition",
    "Reset",
    "Sacrificial Healing",
    "Sudden Stampede",
    "Trollish Charge",
    "Babble",
    "Battle Mind",
    "Convey Inner Peace",
    "Enchanted Bloom",
    "Ethereal Stairs",
    "Maim",
    "Mind Maze",
    "Long Game",
    "Mirror Realm",
    "Door of the Far Traveler",
    "Furious Wail",
  ],
  Cleric: [
    "Adjust Position",
    "Divine Retribution",
    "Feint",
    "Gird the Spirit",
    "Less Fool, I",
    "Lightless Torch",
    "Muted Foe",
    "Outmaneuver",
    "Rockfall Ward",
    "Stone Aegis",
    "Subliminal Aversion",
    "Fuse Armor",
    "Mantle of the Brave",
    "Portal Trap",
    "Shadow's Brand",
    "Sightburst",
    "Silvershout",
    "Bardo",
    "Blunted Edge",
    "Inexorable Summons",
    "Invested Champion",
    "Iron Gut",
    "Life from Death",
    "Never Surrender",
    "Oathbound Implement",
    "Spiked Barricade",
    "Forced Reposition",
    "Harry",
    "Hypnagogia",
    "Inspiring Speech",
    "Reaper's Knell",
    "Repulsing Wall",
    "Reset",
    "Rive",
    "Stone Fetch",
    "Trollish Charge",
    "War Horn",
    "Convey Inner Peace",
    "Ethereal Stairs",
    "Lay to Rest",
    "Maim",
    "Pierce the Veil",
    "Mind Maze",
    "Conjure Spectral Allies",
    "Immolating Gibbet",
    "Door of the Far Traveler",
  ],
  Druid: [
    "Tree Heal",
    "Ambush",
    "Bloodhound",
    "Gird the Spirit",
    "Illuminate Spoor",
    "Rockfall Ward",
    "Stone Aegis",
    "Subliminal Aversion",
    "Bombardment of Stings",
    "Butterfly Effect",
    "Calm Beasts",
    "Magma Spray",
    "Mark Prey",
    "Mud",
    "Oversized Paws",
    "Shadow Tree",
    "Shocking Volley",
    "Threshold Slip",
    "Toothless Beast",
    "Burst Stone",
    "Going in Circles",
    "Steam Gout",
    "Tracer",
    "Vine Carpet",
    "Beast Within",
    "Crown of Thorns",
    "Harry",
    "Hunting Stand",
    "Hypnagogia",
    "Mass Faerie Fire",
    "Reset",
    "Rive",
    "Storm of Wings",
    "Sudden Slue",
    "Sudden Stampede",
    "Convey Inner Peace",
    "Enchanted Bloom",
    "Harrying Hounds",
    "Maim",
    "Toadstool Ring",
    "Wild Hunt",
    "Door of the Far Traveler",
    "Eruption",
    "Furious Wail",
  ],
  Paladin: [
    "Divine Retribution",
    "Feint",
    "Gird the Spirit",
    "Heart to Heart",
    "Litany of Sure Hands",
    "Outmaneuver",
    "Lance",
    "Mantle of the Brave",
    "Safe Transposition",
    "Bardo",
    "Invested Champion",
    "Life from Death",
    "Martyr's Rally",
    "Never Surrender",
    "Inspiring Speech",
    "Repulsing Wall",
    "Reset",
    "War Horn",
    "Battle Mind",
    "Lay to Rest",
    "Life Burst",
    "Pierce the Veil",
  ],
  Ranger: [
    "Abrupt Hug",
    "Ambush",
    "Bloodhound",
    "Hunter's Endurance",
    "Illuminate Spoor",
    "Jarring Growl",
    "Suppress Regeneration",
    "Bombardment of Stings",
    "Calm Beasts",
    "Dead Walking",
    "Instant Snare",
    "Mark Prey",
    "Oversized Paws",
    "Shadow Tree",
    "Shadow's Brand",
    "Shocking Volley",
    "Toothless Beast",
    "Going in Circles",
    "Never Surrender",
    "Piper's Lure",
    "Tracer",
    "Vine Carpet",
    "Beast Within",
    "Harry",
    "Heart-Seeking Arrow",
    "Hunting Stand",
    "Storm of Wings",
    "Sudden Stampede",
    "Harrying Hounds",
    "Killing Fields",
  ],
  Sorcerer: [
    "Ambush",
    "Bloodhound",
    "Glare",
    "Heart to Heart",
    "Ill-Fated Word",
    "Lightless Torch",
    "Muted Foe",
    "Outmaneuver",
    "Rockfall Ward",
    "Sneer",
    "Suppress Regeneration",
    "Betraying Bauble",
    "Bombardment of Stings",
    "Butterfly Effect",
    "Dead Walking",
    "Fey-Touched Blade",
    "Frenzied Bolt",
    "Fuse Armor",
    "Magma Spray",
    "Portal Trap",
    "Shadow Tree",
    "Shadow's Brand",
    "Sightburst",
    "Smelting Blast",
    "Spite",
    "Toothless Beast",
    "Ambush Chute",
    "Armored Formation",
    "Bardo",
    "Blunted Edge",
    "Bound Haze",
    "Burst Stone",
    "Emerald Eyes",
    "Fey Food",
    "Going in Circles",
    "High Ground",
    "Inexorable Summons",
    "Iron Gut",
    "Jagged Forcelance",
    "Piper's Lure",
    "Portal Jaunt",
    "Power Word Fling",
    "Secret Blind",
    "Steam Gout",
    "Crown of Thorns",
    "Forced Reposition",
    "Harry",
    "Power Word Rend",
    "Reaper's Knell",
    "Reposition",
    "Sacrificial Healing",
    "Stone Fetch",
    "Trollish Charge",
    "Babble",
    "Battle Mind",
    "Convey Inner Peace",
    "Deadly Salvo",
    "Enchanted Bloom",
    "Harrying Hounds",
    "Maim",
    "Toadstool Ring",
    "Immolating Gibbet",
    "Long Game",
    "Mirror Realm",
    "Wild Hunt",
    "Devouring Darkness",
    "Furious Wail",
  ],
  Warlock: [
    "Adjust Position",
    "Damaging Intel",
    "Feint",
    "Glare",
    "Hunter's Endurance",
    "Jarring Growl",
    "Lightless Torch",
    "Muted Foe",
    "Outmaneuver",
    "Rockfall Ward",
    "Sneer",
    "Stone Aegis",
    "Suppress Regeneration",
    "Betraying Bauble",
    "Butterfly Effect",
    "Dead Walking",
    "Fuse Armor",
    "Magma Spray",
    "Portal Trap",
    "Shadow's Brand",
    "Sightburst",
    "Smelting Blast",
    "Threshold Slip",
    "Toothless Beast",
    "Ambush Chute",
    "Armored Formation",
    "Blunted Edge",
    "Bound Haze",
    "Burst Stone",
    "Dimensional Shove",
    "Emerald Eyes",
    "Fey Food",
    "Going in Circles",
    "Inexorable Summons",
    "Jagged Forcelance",
    "Power Word Fling",
    "Reciprocating Portal",
    "Secret Blind",
    "Steam Gout",
    "Beast Within",
    "Crown of Thorns",
    "Forced Reposition",
    "Power Word Rend",
    "Reaper's Knell",
    "Reposition",
    "Repulsing Wall",
    "Rive",
    "Sacrifice Pawn",
    "Stone Fetch",
    "Trollish Charge",
    "Convey Inner Peace",
    "Enchanted Bloom",
    "Harrying Hounds",
    "Pierce the Veil",
    "Conjure Spectral Allies",
    "Immolating Gibbet",
    "Long Game",
    "Wild Hunt",
    "Furious Wail",
  ],
  Wizard: [
    "Hypnic Jerk",
    "Adjust Position",
    "Ambush",
    "Bloodhound",
    "Feint",
    "Heart to Heart",
    "Ill-Fated Word",
    "Lightless Torch",
    "Misdirection",
    "Muted Foe",
    "Outmaneuver",
    "Protection from the Void",
    "Retribution",
    "Rockfall Ward",
    "Sneer",
    "Subliminal Aversion",
    "Suppress Regeneration",
    "Betraying Bauble",
    "Bloodlust",
    "Bombardment of Stings",
    "Butterfly Effect",
    "Dead Walking",
    "Frenzied Bolt",
    "Fuse Armor",
    "Glyph of Shifting",
    "Lance",
    "Magma Spray",
    "Mud",
    "Portal Trap",
    "Shadow Tree",
    "Shadow's Brand",
    "Shocking Volley",
    "Sightburst",
    "Smelting Blast",
    "Spite",
    "Threshold Slip",
    "Toothless Beast",
    "Ambush Chute",
    "Armored Formation",
    "Bardo",
    "Blunted Edge",
    "Bolster Fortifications",
    "Bound Haze",
    "Burst Stone",
    "Dimensional Shove",
    "Emerald Eyes",
    "Fey Food",
    "Going in Circles",
    "High Ground",
    "Inexorable Summons",
    "Iron Gut",
    "Jagged Forcelance",
    "Piper's Lure",
    "Portal Jaunt",
    "Power Word Fling",
    "Rebounding Bolt",
    "Reciprocating Portal",
    "Secret Blind",
    "Spiked Barricade",
    "Steam Gout",
    "Crown of Thorns",
    "Dreamwine",
    "Forced Reposition",
    "Harry",
    "Hypnagogia",
    "Power Word Rend",
    "Reaper's Knell",
    "Reposition",
    "Repulsing Wall",
    "Reset",
    "Rive",
    "Sacrifice Pawn",
    "Sacrificial Healing",
    "Stone Fetch",
    "Trollish Charge",
    "War Horn",
    "Babble",
    "Battle Mind",
    "Convey Inner Peace",
    "Deadly Salvo",
    "Enchanted Bloom",
    "Ethereal Stairs",
    "Harrying Hounds",
    "Maim",
    "Pierce the Veil",
    "Conjure Construct",
    "Gale",
    "Instant Armored Vehicle",
    "Mind Maze",
    "Pincer",
    "Toadstool Ring",
    "Clear the Board",
    "Conjure Spectral Allies",
    "Immolating Gibbet",
    "Long Game",
    "Mirror Realm",
    "Door of the Far Traveler",
    "Devouring Darkness",
    "Eruption",
    "Furious Wail",
  ],
};

/** Read the publisher's explicit class assignments without inferring character options. */
export function tomeOfHeroesClasses(name: string): string[] {
  return Object.entries(TOME_OF_HEROES_CLASS_LISTS)
    .filter(([, names]) => names.includes(name))
    .map(([className]) => className);
}
